/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "tao的blog",
  "description": "description",
  "base": "/test2021_11_22/",
  "headTags": [
    [
      "meta",
      {
        "name": "keywords",
        "content": "tao,blog"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "$withBase('/favicon.ico')"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-c91e1a7a",
      "path": "/",
      "lastUpdated": "2021年11月22日星期一晚上11点46分"
    },
    {
      "title": "介绍",
      "frontmatter": {
        "title": "介绍"
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-c050bd70",
      "path": "/css/",
      "lastUpdated": "2021年11月22日星期一晚上11点46分"
    },
    {
      "title": "About me",
      "frontmatter": {
        "navbar": false,
        "title": "About me"
      },
      "regularPath": "/about1.html",
      "relativePath": "about1.md",
      "key": "v-38ebf9c8",
      "path": "/about1.html",
      "headers": [
        {
          "level": 2,
          "title": "yes it's true",
          "slug": "yes-it-s-true"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "1.二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-2"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-3"
        }
      ],
      "lastUpdated": "2021年11月22日星期一晚上11点46分"
    },
    {
      "title": "About me",
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-389c8f18",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "yes it's true",
          "slug": "yes-it-s-true"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "1.二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-2"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-3"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-4"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-5"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题-6"
        }
      ],
      "lastUpdated": "2021年11月25日星期四上午9点45分"
    },
    {
      "title": "默认主题配置",
      "frontmatter": {
        "title": "默认主题配置",
        "sidebarDepth": 2
      },
      "regularPath": "/css/c-a.html",
      "relativePath": "css/c-a.md",
      "key": "v-284c9f6a",
      "path": "/css/c-a.html",
      "headers": [
        {
          "level": 2,
          "title": "首页",
          "slug": "首页"
        },
        {
          "level": 2,
          "title": "导航栏",
          "slug": "导航栏"
        },
        {
          "level": 3,
          "title": "导航栏Logo",
          "slug": "导航栏logo"
        },
        {
          "level": 3,
          "title": "导航栏链接",
          "slug": "导航栏链接"
        },
        {
          "level": 3,
          "title": "禁用导航栏",
          "slug": "禁用导航栏"
        },
        {
          "level": 2,
          "title": "侧边栏",
          "slug": "侧边栏"
        },
        {
          "level": 3,
          "title": "侧边栏1",
          "slug": "侧边栏1"
        },
        {
          "level": 3,
          "title": "侧边栏2",
          "slug": "侧边栏2"
        },
        {
          "level": 3,
          "title": "侧边栏3",
          "slug": "侧边栏3"
        },
        {
          "level": 3,
          "title": "侧边栏4",
          "slug": "侧边栏4"
        },
        {
          "level": 3,
          "title": "侧边栏5",
          "slug": "侧边栏5"
        },
        {
          "level": 2,
          "title": "搜索框",
          "slug": "搜索框"
        }
      ],
      "lastUpdated": "2021年11月22日星期一晚上11点46分"
    },
    {
      "title": "使用插件",
      "frontmatter": {
        "title": "使用插件",
        "sidebarDepth": 2
      },
      "regularPath": "/javascript/j-a.html",
      "relativePath": "javascript/j-a.md",
      "key": "v-1d127159",
      "path": "/javascript/j-a.html",
      "headers": [
        {
          "level": 2,
          "title": "使用插件",
          "slug": "使用插件"
        },
        {
          "level": 2,
          "title": "使用来自依赖的插件",
          "slug": "使用来自依赖的插件"
        },
        {
          "level": 3,
          "title": "插件的缩写",
          "slug": "插件的缩写"
        },
        {
          "level": 3,
          "title": "导航栏链接",
          "slug": "导航栏链接"
        },
        {
          "level": 3,
          "title": "禁用导航栏",
          "slug": "禁用导航栏"
        },
        {
          "level": 2,
          "title": "侧边栏",
          "slug": "侧边栏"
        },
        {
          "level": 3,
          "title": "侧边栏1",
          "slug": "侧边栏1"
        },
        {
          "level": 3,
          "title": "侧边栏2",
          "slug": "侧边栏2"
        },
        {
          "level": 3,
          "title": "侧边栏3",
          "slug": "侧边栏3"
        },
        {
          "level": 3,
          "title": "侧边栏4",
          "slug": "侧边栏4"
        },
        {
          "level": 3,
          "title": "侧边栏5",
          "slug": "侧边栏5"
        },
        {
          "level": 2,
          "title": "搜索框",
          "slug": "搜索框"
        }
      ],
      "lastUpdated": "2021年11月22日星期一晚上11点46分"
    },
    {
      "title": "介绍",
      "frontmatter": {
        "title": "介绍"
      },
      "regularPath": "/javascript/",
      "relativePath": "javascript/README.md",
      "key": "v-1c70eb74",
      "path": "/javascript/",
      "lastUpdated": "2021年11月22日星期一晚上11点46分"
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "关于",
        "link": "/about"
      },
      {
        "text": "主题",
        "link": "/css/"
      },
      {
        "text": "插件",
        "link": "/javascript/"
      },
      {
        "text": "语言",
        "items": [
          {
            "text": "中文",
            "link": "#"
          },
          {
            "text": "英文",
            "link": "#"
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ],
    "sidebar": {
      "/css/": [
        "",
        "c-a"
      ],
      "/javascript/": [
        "",
        "j-a"
      ],
      "/": [
        "about"
      ]
    }
  }
}